- name: Install apt-transport-https
  apt:
     name:
       - apt-transport-https
       - ca-certificates
       - lsb-release
       - gnupg
     state: latest
     update_cache: true

- name: Add signing key
  apt_key:
     url: "https://download.docker.com/linux/ubuntu/gpg"
     state: present

- name: Add repository into sources list
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true
