- name: install mariadb
  apt: name=mariadb-server update_cache=yes state=latest

- name: install pip
  apt: name=pip state=latest

- name: install pymysql
  pip: name=pymysql state=present

- name: passwd user root mysql
  mysql_user:
        login_user: root
        login_password: "{{pass}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        user: root
        check_implicit_admin: true
        password: "{{pass}}"
        priv: "*.*:ALL,GRANT"
        host: localhost
  when: inventory_hostname == "DB_01"

- name: config mariadb
  template:
          src: 50-server.cnf.j2
          dest: /etc/mysql/mariadb.conf.d/50-server.cnf
  notify:
          - restart mariadb

- name: config galera cluster
  template:
          src: galera.cnf.j2
          dest: /etc/mysql/mariadb.conf.d/galera.cnf

- name: add server to cluster
  command: /usr/bin/galera_new_cluster
  when: inventory_hostname == "DB_01"
  notify:
        - restart mariadb
- name: restart service
  command: echo "start service"

  notify:
          - enable mariadb
          - start mariadb


