- name: install redis
  apt: name=redis-server update_cache=yes state=latest

- name: install sentinel
  apt: name=redis-sentinel state=latest

- name: enable vm overcommit
  sysctl:
    name: vm.overcommit_memory
    value: 1
    state: present
    reload: yes
  notify:
          restart redis

- name: config redis
  template:
          src: redis.conf.j2
          dest: /etc/redis/redis.conf

- name: config sentinel
  template:
          src: sentinel.conf.j2
          dest: /etc/redis/sentinel.conf

- name: restart all service
  command:
          echo "restart service"
  notify:
          - restart redis
       
