- name: Create user to server
  user:
    name: "{{ item.user }}"
    shell: /bin/bash
    createhome: yes
    state: present
  with_items:
      - "{{ user_info }}"

- name:  Set up multiple authorized keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.authorized_key }}"
    state: present
    exclusive: True
  with_items:
      - "{{ user_info }}"

- name: Allow sudoer
  lineinfile:
    path: /etc/sudoers.d/{{ item.user }}
    line: '%{{ item.user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  with_items:
      - "{{ user_info }}"

- name: Remove the user
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: 
    - "{{ user_delete }}"
- name: Remove sudoers
  file:
    path: /etc/sudoers.d/{{ item }}
    state: absent
  with_items:
    - "{{ user_delete }}"
