- name: Create user to server
  user:
    name: "{{ user_info.user }}"
    shell: /bin/bash
    createhome: yes
    state: present

- name:  Set up multiple authorized keys
  authorized_key:
    user: "{{ user_info.user }}"
    key: "{{ user_info.authorized_key }}"
    state: present
    exclusive: True

- name: Allow sudoer
  lineinfile:
    path: /etc/sudoers.d/{{ user_info.user }}
    line: '%{{ user_info.user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

